### ISSUE TITLE
problemas con algunos feeds

### ISSUE THREAD

**Issue by victorhck** [selairi/planetlibre#6]
Hola!
Recientemente he añadido los feeds de [este blog](https://ubuntuperonista.blogspot.com/) y no aparecen en la salida. 
Supongo que habrá algún problema con el tipo de feeds.
Muchas gracias por tu tiempo y por tu código! :)

Saludos.

**Comment by selairi** [comment]
Hola, me pongo a mirarlo.
Un saludo

**Comment by selairi** [comment]
Hola, lo he probado a añadir usando:

https://ubuntuperonista.blogspot.com/feeds/posts/default?alt=rss

y me funciona correctamente.

Prueba y me cuentas.

Gracias por tu labor de mantenimiento de tu planeta. Que sepas que lo
visito un día sí y otro también.

Un saludo

**Comment by victorhck** [comment]
Hola!
He usado esa url y sigue sin funcionarme, no aparecen sus feeds en el index...

**Comment by selairi** [comment]
Necesito entonces que me mandes tu archivo blogs_feeds.txt.

También se podría deber a algún fallo el feeds.db. Prueba a borrar feeds.db.

Un saludo

El lunes, 9 de octubre de 2023, Victorhck ***@***.***>
escribió:
> Hola!
> He usado esa url y sigue sin funcionarme, no aparecen sus feeds en el
index...
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci6.googleusercontent.com/proxy/oZCCjU4dr7lGJotRrn2AjKTsruaVll553yWY5kxhRVdHVc86dw0u0t0_j1ihEglNOsQ4hiKjrN7jtFkjAGCfJltw9zunIG6xrMNQ9CYz78lbfZGNk657t2hXkC567jZnawoPcuMwpI231aBwexgkxkr7ibruLAfQkBN4USG2SgsVblr9cXTT53udlE6mIMtpr6EmmMet1oFHtUDlLdkjlTviIkDXDb_qb33pjoTiKxob23xkGQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAI37A6HGT2CVQGH45TQHETX6QKZBA5CNFSM6AAAAAA5WAQDVGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTIQBJYM.gif>Message
ID: ***@***.***>

**Comment by victorhck** [comment]
> Necesito entonces que me mandes tu archivo blogs_feeds.txt.

Está en el repositorio en GitLab

https://gitlab.com/victorhck/planetalibre/-/blob/master/public/blogs_feeds.txt?ref_type=heads

> También se podría deber a algún fallo el feeds.db. Prueba a borrar feeds.db.

Probaré...
Muchas gracias por tu soporte!

**Comment by selairi** [comment]
No localizo el problema. Puede ser un problema de versiones o alguna otra cosa más específica.
Necesito lo siguiente:
No hace falta que toques tu script del planet que tienes en producción. Esto hazlo en otra carpeta.
 Prueba a descargar el planet desde el repositorio en la máquina en el que lo usas de forma habitual:
[https://github.com/selairi/planetlibre/archive/refs/heads/master.zip](https://github.com/selairi/planetlibre/archive/refs/heads/master.zip)
y prueba a simplemente ejecutarlo con:
`python3 planet.py`
**y mira si en `salida/index.html` que genera te aparecen las entradas desaparecidas**. He cogido tu archivo de feeds y lo he copiado al repositorio (de paso he limpiado blogs que han desaparecido y otros que han cambiado la forma de obtener los feeds), por lo que no hace falta que copies tu archivo de feeds.

- Si no aparecen las entradas, puede que sea un problema de versiones, entonces necesitaría la versión de tu sistema operativo (supongo que lo ejecutas en la Raspberry Pi) y la versión de tu biblioteca "feedparser" (`pip3 show feedparser`). Para que te hagas una idea, mi versión de feedparser es 6.0.10. No te arriesgues todavía a actualizar tu biblioteca feedparser (`pip3 install --upgrade feedparser`), regla del "si funciona, no lo toques".
- Si aparecen las entradas, será un problema adicional que tenemos que resolver.

Un saludo y gracias

**Comment by victorhck** [comment]
Al ejecutar `pip3 show feedparser` me da el error:
Violación de segmento
tampoco me deja actualizarlo...

**Comment by selairi** [comment]
¿Has probado con sudo?

**Comment by victorhck** [comment]
Hola!
Cierro el issue, porque todo parece haberse solucionado. Use la Pi para otros proyectos, y después de pruebas, volví a instalar Raspbian, una versión actualizada.
Después de unos problemas iniciales, todo parece volver a funcionar correctamente en la Pi.
Muchas gracias de nuevo por todo!! :)
