### ISSUE TITLE
error al parsear un &

### ISSUE THREAD

**Issue by victorhck** [selairi/planetlibre#8]
Hola.
Se pone en contacto conmigo un lector de PlanetaLibre que dice que le sale un error al obtener los feeds de PlanetaLibre:

`error on line 40 at column 169: EntityRef: expecting ';'`

Parece que el problema viene con este feed:

`https://blog.bricogeek.com/noticias/raspberry-pi/buscando-a-wally-con-google-cloud-automl-raspberry-pi-y-un-brazo-robot/?utm_source=blogfeed&utm_medium=atom10&utm_term=raspberry-pi&utm_content=buscando-a-wally-con-google-cloud-automl-raspberry-pi-y-un-brazo-robot&utm_campaign=blog`

Por los símbolos &
No se me ocurre una solución...
Muchas gracias por tu tiempo. Saludos!

**Comment by selairi** [comment]
Hola, el problema ya ha sido resuelto, por lo que a partir de ahora no debería dar problemas.
También he hecho cambios en la forma en el que el script genera la tabla de noticias de forma que ahora, en lugar de una tabla, se generan div. De esta forma es más fácil hacer que el diseño se adapte a móviles.
Si necesitas algo, me lo comentas.
Un saludo

**Comment by victorhck** [comment]
Muuuuchas gracias por tus soluciones!! :)
Ya ví que habían aportado un PR para solucionar el problema. Quien aportó la solución fue quien me lo comentó por correo :)
Supongo que debería borrar el feed anterior, para que lo volviera a generar ahora de manera correcta ¿no?
Hace unos días cambién el código del index para darle otro aspecto a mi instancia de PlanetaLibre.

Saludos.

**Comment by victorhck** [comment]
Por cierto me da este error y creo que no me genera el feed

```
  File "/home/victorhck/Planetas/planeta/planet.py", line 147, in generar_rss
    </item>""".format(blog=clean_html(row[0]), titulo=clean_html(row[1]), enlace=clean_html(row[2]), fecha=clean_html(time.asctime(fecha))))
                           ^^^^^^^^^^
NameError: name 'clean_html' is not defined
```

**Comment by selairi** [comment]
¿Error en la línea 147? No puede ser, esa línea que aparece ahí debería ser la 153.
¿¿¿???
Prueba descargar el repositorio y lo ejecutas cambiando el archivo "blog_feeds.txt" por el tuyo. Debería funcionar a la primera. Tendrás que echar un ojo al archivo "cabecera.html" para copiarle el estilo que has escrito.

Efectivamente tendrás que borrar el archivo "feeds.db" para eliminar el error anterior.

Un saludo, si necesitas ayuda no dudes en contactar y si es necesario hacemos un Jitsi.

**Comment by victorhck** [comment]
Bueno, igual tengo menos líneas que el script original por un motivo (no sé ahora cual será)
Pero ¿Por qué me da ese error?

**Comment by selairi** [comment]
Si te está dando ese error, es que te faltan las líneas 50 y 51 del script:
https://github.com/selairi/planetlibre/blob/05983e135f19592649cfc957354ab1e03ec9bce9/planet.py#L50-L51

Creo que estás 4 versiones por detrás de la versión actual. Concretamente en esta versión:
https://github.com/selairi/planetlibre/blob/07105ab7d71b50d58a0f7c2198df7eb5fd637120/planet.py

Un saludo

**Comment by victorhck** [comment]
creí haber copiado todo lo necesario y lo que ví en el commit... pero efectivamente me faltaban esas líneas.
Ya todo vuelve a funcionar Ok.
Muchas gracias por todo!!! :)
Saludos.
